# Etapa 1: Construcción
FROM node:18-alpine AS builder

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos del proyecto
COPY package*.json ./
COPY yarn.lock ./
COPY . .

# Instalar dependencias
RUN yarn install

# Compilar la aplicación
RUN yarn build

# Etapa 2: Servidor NGINX para producción
FROM nginx:stable-alpine

# Copiar archivos de compilación a la ruta por defecto de NGINX
COPY --from=builder /app/dist /usr/share/nginx/html

# Eliminar configuración por defecto de NGINX
RUN rm /etc/nginx/conf.d/default.conf

# Copiar configuración personalizada
COPY nginx.conf /etc/nginx/conf.d

# Exponer el puerto por defecto
EXPOSE 80

# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
