# Solo NGINX
FROM nginx:stable-alpine

# Copiar archivos de build generados por GitHub Actions
COPY ./dist /usr/share/nginx/html

# Eliminar configuración por defecto de NGINX
RUN rm /etc/nginx/conf.d/default.conf

# Copiar configuración personalizada
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
