version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: netcomputer_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - netcomputer-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netcomputer_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - netcomputer-network

  mongodb:
    image: mongo:6.0
    container_name: netcomputer_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - netcomputer-network

volumes:
  mongo_data:

networks:
  netcomputer-network:
    driver: bridge
