version: "3.8"

services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-network

  nginx_letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx_letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy
      - DEFAULT_EMAIL=3003html@gmail.com
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx_proxy
    networks:
      - nginx-network

  frontend_staging:
    image: ghcr.io/chriscodex/frontend:staging-latest
    container_name: frontend_staging
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=app.staging.chriscodex.online
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=app.staging.chriscodex.online
    networks:
      - nginx-network

  backend_staging:
    image: ghcr.io/chriscodex/backend:staging-latest
    container_name: backend_staging
    restart: unless-stopped
    env_file:
      - .env.staging
    environment:
      - VIRTUAL_HOST=api.staging.chriscodex.online
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.staging.chriscodex.online
    networks:
      - nginx-network

  mongodb_staging:
    image: mongo:6.0
    container_name: mongodb_staging
    volumes:
      - mongo_data:/data/db
    networks:
      - nginx-network

volumes:
  mongo_data:

networks:
  nginx-network:
    external: true
